/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ca_uwaterloo_JCLCudaAPI_Queue */

#ifndef _Included_ca_uwaterloo_JCLCudaAPI_Queue
#define _Included_ca_uwaterloo_JCLCudaAPI_Queue
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ca_uwaterloo_JCLCudaAPI_Queue
 * Method:    init
 * Signature: (Lca/uwaterloo/JCLCudaAPI/Context;Lca/uwaterloo/JCLCudaAPI/Device;)V
 */
JNIEXPORT void JNICALL Java_ca_uwaterloo_JCLCudaAPI_Queue_init
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     ca_uwaterloo_JCLCudaAPI_Queue
 * Method:    finish
 * Signature: (Lca/uwaterloo/JCLCudaAPI/Event;)V
 */
JNIEXPORT void JNICALL Java_ca_uwaterloo_JCLCudaAPI_Queue_finish__Lca_uwaterloo_JCLCudaAPI_Event_2
  (JNIEnv *, jobject, jobject);

/*
 * Class:     ca_uwaterloo_JCLCudaAPI_Queue
 * Method:    finish
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ca_uwaterloo_JCLCudaAPI_Queue_finish__
  (JNIEnv *, jobject);

/*
 * Class:     ca_uwaterloo_JCLCudaAPI_Queue
 * Method:    getContext
 * Signature: ()Lca/uwaterloo/JCLCudaAPI/Context;
 */
JNIEXPORT jobject JNICALL Java_ca_uwaterloo_JCLCudaAPI_Queue_getContext
  (JNIEnv *, jobject);

/*
 * Class:     ca_uwaterloo_JCLCudaAPI_Queue
 * Method:    getDevice
 * Signature: ()Lca/uwaterloo/JCLCudaAPI/Device;
 */
JNIEXPORT jobject JNICALL Java_ca_uwaterloo_JCLCudaAPI_Queue_getDevice
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
