/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ca_uwaterloo_JCLCudaAPI_CudaEvent */

#ifndef _Included_ca_uwaterloo_JCLCudaAPI_CudaEvent
#define _Included_ca_uwaterloo_JCLCudaAPI_CudaEvent
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ca_uwaterloo_JCLCudaAPI_CudaEvent
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ca_uwaterloo_JCLCudaAPI_CudaEvent_init
  (JNIEnv *, jobject);

/*
 * Class:     ca_uwaterloo_JCLCudaAPI_CudaEvent
 * Method:    getElapsedTime
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_ca_uwaterloo_JCLCudaAPI_CudaEvent_getElapsedTime
  (JNIEnv *, jobject);

/*
 * Class:     ca_uwaterloo_JCLCudaAPI_CudaEvent
 * Method:    waitForCompletion
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ca_uwaterloo_JCLCudaAPI_CudaEvent_waitForCompletion
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
