/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ca_uwaterloo_JCLCudaAPI_Event */

#ifndef _Included_ca_uwaterloo_JCLCudaAPI_Event
#define _Included_ca_uwaterloo_JCLCudaAPI_Event
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ca_uwaterloo_JCLCudaAPI_Event
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ca_uwaterloo_JCLCudaAPI_Event_init
  (JNIEnv *, jobject);

/*
 * Class:     ca_uwaterloo_JCLCudaAPI_Event
 * Method:    getElapsedTime
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_ca_uwaterloo_JCLCudaAPI_Event_getElapsedTime
  (JNIEnv *, jobject);

/*
 * Class:     ca_uwaterloo_JCLCudaAPI_Event
 * Method:    waitForCompletion
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ca_uwaterloo_JCLCudaAPI_Event_waitForCompletion
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
