/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ca_uwaterloo_JCLCudaAPI_Context */

#ifndef _Included_ca_uwaterloo_JCLCudaAPI_Context
#define _Included_ca_uwaterloo_JCLCudaAPI_Context
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ca_uwaterloo_JCLCudaAPI_Context
 * Method:    init
 * Signature: (Lca/uwaterloo/JCLCudaAPI/Device;)V
 */
JNIEXPORT void JNICALL Java_ca_uwaterloo_JCLCudaAPI_Context_init
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
