/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ca_uwaterloo_JCLCudaAPI_BufferHost */

#ifndef _Included_ca_uwaterloo_JCLCudaAPI_BufferHost
#define _Included_ca_uwaterloo_JCLCudaAPI_BufferHost
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ca_uwaterloo_JCLCudaAPI_BufferHost
 * Method:    init
 * Signature: (Lca/uwaterloo/JCLCudaAPI/Context;J)V
 */
JNIEXPORT void JNICALL Java_ca_uwaterloo_JCLCudaAPI_BufferHost_init
  (JNIEnv *, jobject, jobject, jlong);

/*
 * Class:     ca_uwaterloo_JCLCudaAPI_BufferHost
 * Method:    getByteBuffer
 * Signature: ()Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_ca_uwaterloo_JCLCudaAPI_BufferHost_getByteBuffer
  (JNIEnv *, jobject);

/*
 * Class:     ca_uwaterloo_JCLCudaAPI_BufferHost
 * Method:    getSize
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_ca_uwaterloo_JCLCudaAPI_BufferHost_getSize
  (JNIEnv *, jobject);

/*
 * Class:     ca_uwaterloo_JCLCudaAPI_BufferHost
 * Method:    size
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_ca_uwaterloo_JCLCudaAPI_BufferHost_size
  (JNIEnv *, jobject);

/*
 * Class:     ca_uwaterloo_JCLCudaAPI_BufferHost
 * Method:    getNativePointerAddress
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_ca_uwaterloo_JCLCudaAPI_BufferHost_getNativePointerAddress
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
