/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ca_uwaterloo_JCLCudaAPI_CudaContext */

#ifndef _Included_ca_uwaterloo_JCLCudaAPI_CudaContext
#define _Included_ca_uwaterloo_JCLCudaAPI_CudaContext
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ca_uwaterloo_JCLCudaAPI_CudaContext
 * Method:    init
 * Signature: (Lca/uwaterloo/JCLCudaAPI/CudaDevice;)V
 */
JNIEXPORT void JNICALL Java_ca_uwaterloo_JCLCudaAPI_CudaContext_init
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
