/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ca_uwaterloo_JCLCudaAPI_BufferHost_DataType */

#ifndef _Included_ca_uwaterloo_JCLCudaAPI_BufferHost_DataType
#define _Included_ca_uwaterloo_JCLCudaAPI_BufferHost_DataType
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
