/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ca_uwaterloo_JCLCudaAPI_CudaPlatform */

#ifndef _Included_ca_uwaterloo_JCLCudaAPI_CudaPlatform
#define _Included_ca_uwaterloo_JCLCudaAPI_CudaPlatform
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ca_uwaterloo_JCLCudaAPI_CudaPlatform
 * Method:    init
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_ca_uwaterloo_JCLCudaAPI_CudaPlatform_init
  (JNIEnv *, jobject, jlong);

/*
 * Class:     ca_uwaterloo_JCLCudaAPI_CudaPlatform
 * Method:    numDevices
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_ca_uwaterloo_JCLCudaAPI_CudaPlatform_numDevices
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
