/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ca_uwaterloo_JCLCudaAPI_Platform */

#ifndef _Included_ca_uwaterloo_JCLCudaAPI_Platform
#define _Included_ca_uwaterloo_JCLCudaAPI_Platform
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ca_uwaterloo_JCLCudaAPI_Platform
 * Method:    init
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_ca_uwaterloo_JCLCudaAPI_Platform_init
  (JNIEnv *, jobject, jint);

/*
 * Class:     ca_uwaterloo_JCLCudaAPI_Platform
 * Method:    numDevices
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_ca_uwaterloo_JCLCudaAPI_Platform_numDevices
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
