/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ca_uwaterloo_JCLCudaAPI_Program */

#ifndef _Included_ca_uwaterloo_JCLCudaAPI_Program
#define _Included_ca_uwaterloo_JCLCudaAPI_Program
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ca_uwaterloo_JCLCudaAPI_Program
 * Method:    init
 * Signature: (Lca/uwaterloo/JCLCudaAPI/Context;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_ca_uwaterloo_JCLCudaAPI_Program_init
  (JNIEnv *, jobject, jobject, jstring);

/*
 * Class:     ca_uwaterloo_JCLCudaAPI_Program
 * Method:    build_native
 * Signature: (Lca/uwaterloo/JCLCudaAPI/Device;Ljava/util/List;)I
 */
JNIEXPORT jint JNICALL Java_ca_uwaterloo_JCLCudaAPI_Program_build_1native
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     ca_uwaterloo_JCLCudaAPI_Program
 * Method:    getBuildInfo
 * Signature: (Lca/uwaterloo/JCLCudaAPI/Device;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ca_uwaterloo_JCLCudaAPI_Program_getBuildInfo
  (JNIEnv *, jobject, jobject);

/*
 * Class:     ca_uwaterloo_JCLCudaAPI_Program
 * Method:    getIR
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ca_uwaterloo_JCLCudaAPI_Program_getIR
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
