/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ca_uwaterloo_JCLCudaAPI_Kernel */

#ifndef _Included_ca_uwaterloo_JCLCudaAPI_Kernel
#define _Included_ca_uwaterloo_JCLCudaAPI_Kernel
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ca_uwaterloo_JCLCudaAPI_Kernel
 * Method:    init
 * Signature: (Lca/uwaterloo/JCLCudaAPI/Program;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_ca_uwaterloo_JCLCudaAPI_Kernel_init
  (JNIEnv *, jobject, jobject, jstring);

/*
 * Class:     ca_uwaterloo_JCLCudaAPI_Kernel
 * Method:    setArgument
 * Signature: (JLca/uwaterloo/JCLCudaAPI/Buffer;)V
 */
JNIEXPORT void JNICALL Java_ca_uwaterloo_JCLCudaAPI_Kernel_setArgument__JLca_uwaterloo_JCLCudaAPI_Buffer_2
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     ca_uwaterloo_JCLCudaAPI_Kernel
 * Method:    setArgument
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_ca_uwaterloo_JCLCudaAPI_Kernel_setArgument__JI
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     ca_uwaterloo_JCLCudaAPI_Kernel
 * Method:    setArgument
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_ca_uwaterloo_JCLCudaAPI_Kernel_setArgument__JF
  (JNIEnv *, jobject, jlong, jfloat);

/*
 * Class:     ca_uwaterloo_JCLCudaAPI_Kernel
 * Method:    setArgument
 * Signature: (JD)V
 */
JNIEXPORT void JNICALL Java_ca_uwaterloo_JCLCudaAPI_Kernel_setArgument__JD
  (JNIEnv *, jobject, jlong, jdouble);

/*
 * Class:     ca_uwaterloo_JCLCudaAPI_Kernel
 * Method:    localMemUsage
 * Signature: (Lca/uwaterloo/JCLCudaAPI/Device;)J
 */
JNIEXPORT jlong JNICALL Java_ca_uwaterloo_JCLCudaAPI_Kernel_localMemUsage
  (JNIEnv *, jobject, jobject);

/*
 * Class:     ca_uwaterloo_JCLCudaAPI_Kernel
 * Method:    launch
 * Signature: (Lca/uwaterloo/JCLCudaAPI/Queue;[J[JLca/uwaterloo/JCLCudaAPI/Event;)V
 */
JNIEXPORT void JNICALL Java_ca_uwaterloo_JCLCudaAPI_Kernel_launch__Lca_uwaterloo_JCLCudaAPI_Queue_2_3J_3JLca_uwaterloo_JCLCudaAPI_Event_2
  (JNIEnv *, jobject, jobject, jlongArray, jlongArray, jobject);

/*
 * Class:     ca_uwaterloo_JCLCudaAPI_Kernel
 * Method:    launch
 * Signature: (Lca/uwaterloo/JCLCudaAPI/Queue;[J[JLca/uwaterloo/JCLCudaAPI/Event;Ljava/util/List;)V
 */
JNIEXPORT void JNICALL Java_ca_uwaterloo_JCLCudaAPI_Kernel_launch__Lca_uwaterloo_JCLCudaAPI_Queue_2_3J_3JLca_uwaterloo_JCLCudaAPI_Event_2Ljava_util_List_2
  (JNIEnv *, jobject, jobject, jlongArray, jlongArray, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
