/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ca_uwaterloo_JCLCudaAPI_Program_BuildStatus */

#ifndef _Included_ca_uwaterloo_JCLCudaAPI_Program_BuildStatus
#define _Included_ca_uwaterloo_JCLCudaAPI_Program_BuildStatus
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
