/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ca_uwaterloo_JCLCudaAPI_CudaQueue */

#ifndef _Included_ca_uwaterloo_JCLCudaAPI_CudaQueue
#define _Included_ca_uwaterloo_JCLCudaAPI_CudaQueue
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ca_uwaterloo_JCLCudaAPI_CudaQueue
 * Method:    init
 * Signature: (Lca/uwaterloo/JCLCudaAPI/CudaContext;Lca/uwaterloo/JCLCudaAPI/CudaDevice;)V
 */
JNIEXPORT void JNICALL Java_ca_uwaterloo_JCLCudaAPI_CudaQueue_init
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     ca_uwaterloo_JCLCudaAPI_CudaQueue
 * Method:    finish
 * Signature: (Lca/uwaterloo/JCLCudaAPI/Event;)V
 */
JNIEXPORT void JNICALL Java_ca_uwaterloo_JCLCudaAPI_CudaQueue_finish__Lca_uwaterloo_JCLCudaAPI_Event_2
  (JNIEnv *, jobject, jobject);

/*
 * Class:     ca_uwaterloo_JCLCudaAPI_CudaQueue
 * Method:    finish
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ca_uwaterloo_JCLCudaAPI_CudaQueue_finish__
  (JNIEnv *, jobject);

/*
 * Class:     ca_uwaterloo_JCLCudaAPI_CudaQueue
 * Method:    getContext
 * Signature: ()Lca/uwaterloo/JCLCudaAPI/Context;
 */
JNIEXPORT jobject JNICALL Java_ca_uwaterloo_JCLCudaAPI_CudaQueue_getContext
  (JNIEnv *, jobject);

/*
 * Class:     ca_uwaterloo_JCLCudaAPI_CudaQueue
 * Method:    getDevice
 * Signature: ()Lca/uwaterloo/JCLCudaAPI/Device;
 */
JNIEXPORT jobject JNICALL Java_ca_uwaterloo_JCLCudaAPI_CudaQueue_getDevice
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
